# Basic dependabot.yml to update gomod

version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "daily"
      # Check for npm updates at 9am UTC (5am EST)
      time: "10:00"
    reviewers:
      - "rohenaz"
    assignees:
      - "rohenaz"
    # Labels must be created first
    labels:
      - "update"
